---
repos:
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        always_run: true
        pass_filenames: true
        files: '^.+\.pyi?$'
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: check-docstring-first
        exclude: ^docs/
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^docs/
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: ^docs/
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict, -c=./.yamllint]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: ^src/